version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/source
    ports:
      - "8000:8000"
    links:
      - openldap
  openldap-ldifs:
      build: ./ldap
      depends_on:
        - openldap
      entrypoint: sh -c '/ldifs/ldap.sh'
  openldap:
    image: osixia/openldap
    ports:
      - "389:389"
    environment:
      - LDAP_DOMAIN=example.com
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_ADMIN_PASSWORD=mypassword
